spring.application.name=examenApiREST

# MongoDB
spring.mongodb.uri=mongodb+srv://root:rute@cluster0.7tpaxsu.mongodb.net/examenREST?appName=Cluster0
spring.mongodb.database=examenREST

# Swagger
springdoc.swagger-ui.path=/